import { Component } from '@angular/core';

@Component({
  selector: 'app-marvel-list',
  templateUrl: './marvel-list.component.html',
  styleUrls: ['./marvel-list.component.scss'],
})
export class MarvelListComponent {
  tableContent = [
    { id: 12, name: 'Dr.Nice' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Cleiot' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'cleion' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
    { id: 15, name: 'Magneta' },
  ];
}
